In [2]:
import numpy as np
import random 


In [8]:
data = np.load(f'/data/jhahn/data/shape_dataset/results/inference/denoiser_only/0/init_pose.npy')
for item in data:
    try:
        print(item,data[item].shape,data[item])
    except:
        print("ERROR",item)
        pass

ERROR -0.4595237146447638
ERROR -0.9403887644043807
ERROR -0.15706745674594969
ERROR 0.002299885449275422
ERROR 0.3116260310194021
ERROR -0.5190960473435966
ERROR 0.7958788984200229


In [9]:
data = np.load(f'/data/jhahn/data/shape_dataset/results_tg/inference/denoiser_only/0/init_pose.npy')
for item in data:
    try:
        print(item,data[item].shape,data[item])
    except:
        print("ERROR",item)
        pass

ERROR -0.15636965643965342
ERROR -0.5354264164591335
ERROR 0.3272715300851422
ERROR 0.002299885449275422
ERROR 0.3116260310194021
ERROR -0.5190960473435966
ERROR 0.7958788984200229


In [16]:
pc_data_dir = '/data/jhahn/data/shape_dataset/pc_data/val'
print("\n","pc_data")
data_id = '00'
data = np.load(f'{pc_data_dir}/000{data_id}.npz')
for item in data:
    try:
        print(item,data[item].shape,data[item])
    except:
        print("ERROR",item)
        pass


 pc_data
data_id () 0
part_valids (20,) [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_parts () 2
mesh_file_path () brain/2_parts_val/fractured_0
graph (20, 20) [[False  True False False False False False False False False False False
  False False False False False False False False]
 [ True False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False F

In [18]:
_data = data['part_pcs_gt'].reshape((2000,3))

In [19]:
xyz_list = []
for i in range(len(_data)):
    xyz_list.append(_data[i])



with open(f'test2.obj','w') as f:
    for xyz in xyz_list:
        f.write(f'v {xyz[0]} {xyz[1]} {xyz[2]}\n')

In [7]:
print(np.max(data['part_pcs_gt'],axis=1))
print(np.min(data['part_pcs_gt'],axis=1))

[[0.95324675 0.2        0.96356275]
 [0.98097826 0.05       0.95896328]
 [0.98694517 0.75       0.9773913 ]
 [0.94683544 0.9        0.97440273]
 [0.94416244 0.4        0.96153846]
 [0.97435897 0.3        0.97913043]
 [0.96935933 0.95       0.97404844]
 [0.95027624 0.5        0.97391304]
 [0.95786517 0.35       0.97040169]
 [0.95430108 0.85       0.9837587 ]
 [0.97421203 0.15       0.98130841]
 [0.96978022 0.45       0.98300971]
 [0.97714286 0.8        0.98014888]
 [0.9519774  0.65       0.97044335]
 [0.98480243 0.1        0.97612732]
 [0.95692308 0.7        0.97520661]
 [0.94375    0.55       0.9673913 ]
 [0.92079208 0.25       0.97230769]
 [0.92578125 0.6        0.93125   ]
 [0.92982456 1.         0.93050193]]
[[0.04155844 0.15       0.00404858]
 [0.01358696 0.         0.01943844]
 [0.02872063 0.7        0.02086957]
 [0.00253165 0.85       0.02730375]
 [0.00507614 0.35       0.03177258]
 [0.02564103 0.25       0.02086957]
 [0.00278552 0.9        0.01557093]
 [0.02762431 0.45       0.0

In [5]:
print(np.max(data['part_pcs_gt'],axis=1))
print(np.min(data['part_pcs_gt'],axis=1))

[[0.99517533 0.49868585 0.9910262 ]
 [0.99239861 0.99338126 0.99064032]]
[[0.02886727 0.01226331 0.01484838]
 [0.00521229 0.50001268 0.02735267]]


In [2]:
idx = 10
n_pcs = torch.tensor(np.array([[1286, 314,   30,   30 , 366,  301 , 877,  624,  129,  403,  428,  212,    0,    0,  0 ,   0,    0,    0,    0,    0]]))
print(n_pcs.shape)
n_pcs_cumsum = n_pcs.cumsum(dim=1)
print(n_pcs_cumsum)
pc_st1 = 0 if idx == 0 else n_pcs_cumsum[0, idx - 1]
print(pc_st1)
pc_ed1 = n_pcs_cumsum[0, idx]
print(pc_ed1)

torch.Size([1, 20])
tensor([[1286, 1600, 1630, 1660, 2026, 2327, 3204, 3828, 3957, 4360, 4788, 5000,
         5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000]])
tensor(4360)
tensor(4788)


In [3]:
pc_data_dir = '/data/jhahn/data/shape_dataset/pc_data/train'
print("\n","pc_data")
data_id = '00'
data = np.load(f'{pc_data_dir}/000{data_id}.npz')
for item in data:
    try:
        print(item,data[item].shape,data[item])
    except:
        print("ERROR",item)
        pass


 pc_data
data_id () 0
part_valids (20,) [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
num_parts () 2
mesh_file_path () shape/vase/2_parts/fractured_0
graph (20, 20) [[False  True False False False False False False False False False False
  False False False False False False False False]
 [ True False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False]
 [False False False False False False False False False False False 

In [ ]:
data_id = 16

print("matching_data")
data = np.load(f'/disk2/data/breaking-bad-dataset/data/matching_data/{data_id}.npz')
for item in data:
    try:
        print(item,data[item].shape,type(data[item]),data[item])
    except:
        print("ERROR",item)
        pass
    



print("\n","verifier_data")
data = np.load(f'/disk2/data/breaking-bad-dataset/data/verifier_data/{data_id}.npz')
for item in data:
    try:
        print(item,data[item].shape,data[item])
    except:
        print("ERROR",item)
        pass


matching_data
edges (32, 2) <class 'numpy.ndarray'> [[ 1  0]
 [ 5  0]
 [ 6  0]
 [ 7  0]
 [ 9  0]
 [10  0]
 [ 4  1]
 [ 5  1]
 [11  1]
 [ 3  2]
 [ 7  2]
 [11  2]
 [ 8  3]
 [11  3]
 [ 6  5]
 [ 7  5]
 [ 9  5]
 [10  5]
 [11  5]
 [ 7  6]
 [ 8  6]
 [ 9  6]
 [10  6]
 [11  6]
 [ 8  7]
 [10  7]
 [11  7]
 [ 9  8]
 [10  8]
 [10  9]
 [11  9]
 [11 10]]
ERROR correspondence
gt_pcs (5000, 3) <class 'numpy.ndarray'> [[-0.12316637 -0.0748463  -0.21200943]
 [-0.07170958  0.129898    0.05592548]
 [ 0.11838685 -0.07271845  0.06463178]
 ...
 [-0.14312303  0.06455568 -0.4935415 ]
 [-0.09513497  0.02020543 -0.37322292]
 [ 0.00956341  0.00220429 -0.37117305]]
critical_pcs_idx (5000,) <class 'numpy.ndarray'> [0 4 7 ... 0 0 0]
n_pcs (20,) <class 'numpy.ndarray'> [1286  314   30   30  366  301  877  624  129  403  428  212    0    0
    0    0    0    0    0    0]
n_critical_pcs (20,) <class 'numpy.ndarray'> [489 188  30  30  88 285 544 495 129 238 360 196   0   0   0   0   0   0
   0   0]

 pc_data
data_id () 16

In [23]:
mat_mask = torch.triu(torch.ones(20, 20, dtype=torch.bool), diagonal=1)

In [27]:
mat_mask.sum()

tensor(190)

In [ ]:
logits torch.Size([1, 190, 1])