In [1]:

import os
import glob
import torch
import random
import multiprocessing

if torch.cuda.is_available():
    device = torch.device("cuda:0")
    torch.cuda.set_device(device)
else:
    device = torch.device("cpu")
inference_dir = '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100'
data_dir = '/data/jhahn/data/shape_dataset/data'

In [26]:
import importlib
import render_inference_result
import obj_2_pcd
import slice_util
importlib.reload(slice_util)
importlib.reload(obj_2_pcd)
importlib.reload(render_inference_result)

result_dir_list = []
for f in os.listdir(inference_dir):
    if os.path.isdir(inference_dir+"/"+f):
        result_dir_list.append(inference_dir+"/"+f)
print(result_dir_list)

output_dir = 'output'
os.makedirs(output_dir, exist_ok=True)


for _result_dir in result_dir_list[:1]:
    #result_dir = f'{inference_dir}/1'
    data_id = _result_dir.split("/")[-1]

    render_inference_result.gt_img(device,_result_dir, data_dir, output_dir)

    render_inference_result.make_video(device,data_dir,_result_dir,output_dir )


['/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/1', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/0', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/13', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/10', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/2', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/16', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/6', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/14', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/12', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/3', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/7', '/da

100%|██████████| 18/18 [00:00<00:00, 20.55it/s]


(0.11152762174606323, 0.9047377109527588) (-1.5, 1) (0.05692139267921448, 0.7175641059875488)


 11%|█         | 2/18 [00:00<00:01, 12.79it/s]

0 tensor(0.0890, device='cuda:0') tensor(0.0900, device='cuda:0')
1 tensor(0.0960, device='cuda:0') tensor(0.0970, device='cuda:0')
2 tensor(0.1030, device='cuda:0') tensor(0.1040, device='cuda:0')


 22%|██▏       | 4/18 [00:00<00:01, 12.91it/s]

3 tensor(0.1100, device='cuda:0') tensor(0.1110, device='cuda:0')
4 tensor(0.1170, device='cuda:0') tensor(0.1180, device='cuda:0')
5 tensor(0.1240, device='cuda:0') tensor(0.1250, device='cuda:0')


 44%|████▍     | 8/18 [00:00<00:00, 12.96it/s]

6 tensor(0.1310, device='cuda:0') tensor(0.1320, device='cuda:0')
7 tensor(0.1380, device='cuda:0') tensor(0.1390, device='cuda:0')
8 tensor(0.1450, device='cuda:0') tensor(0.1460, device='cuda:0')


 56%|█████▌    | 10/18 [00:00<00:00, 12.93it/s]

9 tensor(0.1520, device='cuda:0') tensor(0.1530, device='cuda:0')
10 tensor(0.1590, device='cuda:0') tensor(0.1600, device='cuda:0')
11 tensor(0.1660, device='cuda:0') tensor(0.1670, device='cuda:0')


 78%|███████▊  | 14/18 [00:01<00:00, 13.00it/s]

12 tensor(0.1730, device='cuda:0') tensor(0.1740, device='cuda:0')
13 tensor(0.1800, device='cuda:0') tensor(0.1810, device='cuda:0')
14 tensor(0.1870, device='cuda:0') tensor(0.1880, device='cuda:0')


 89%|████████▉ | 16/18 [00:01<00:00, 13.02it/s]

15 tensor(0.1940, device='cuda:0') tensor(0.1950, device='cuda:0')
16 tensor(0.2010, device='cuda:0') tensor(0.2020, device='cuda:0')
17 tensor(0.2080, device='cuda:0') tensor(0.2090, device='cuda:0')


100%|██████████| 18/18 [00:01<00:00, 12.98it/s]


['/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/1', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/0', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/13', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/10', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/2', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/16', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/6', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/14', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/12', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/3', '/data/jhahn/data/shape_dataset/inference_results/inference/brain_lightsheet_from_100/7', '/da

 17%|█▋        | 3/18 [00:00<00:00, 21.22it/s]

/data/jhahn/data/shape_dataset/data/brain_lightsheet/0408_0.001_0089_215_rotate_test/fractured_0/0089.obj 0.08900000154972076 0.09000000357627869
/data/jhahn/data/shape_dataset/data/brain_lightsheet/0408_0.001_0089_215_rotate_test/fractured_0/0096.obj 0.09600000083446503 0.09700000286102295
/data/jhahn/data/shape_dataset/data/brain_lightsheet/0408_0.001_0089_215_rotate_test/fractured_0/0103.obj 0.10300000011920929 0.10400000214576721


100%|██████████| 18/18 [00:01<00:00, 16.95it/s]


/data/jhahn/data/shape_dataset/data/brain_lightsheet/0408_0.001_0089_215_rotate_test/fractured_0/0201.obj 0.20100000500679016 0.20200000703334808
/data/jhahn/data/shape_dataset/data/brain_lightsheet/0408_0.001_0089_215_rotate_test/fractured_0/0208.obj 0.20800000429153442 0.20900000631809235


In [ ]:
import numpy as np    

gt = np.load(f'{result_dir}/gt.npy')
print(gt.shape)

init_pose = np.load(f'{result_dir}/init_pose.npy')
print(init_pose.shape)

predict_file_name = glob.glob(f'{result_dir}/predict*')[0]
predict_0 = np.load(predict_file_name)
#predict_0[0,0,:]

In [ ]:

tiff_img_dir = '/data/jhahn/data/brain_lightsheet/0408'
tiff_filename_list = []

for tiff_filename in os.listdir(tiff_img_dir):
    tiff_filename_full = f'{tiff_img_dir}/{tiff_filename}'
    tiff_filename_list.append(tiff_filename_full)
tiff_filename_list.sort(key = lambda x: int(x.split("/")[-1].split(".")[-2]))

#obj_dir = '/data/jhahn/data/shape_dataset/data/brain_lightsheet/0408_0089_215_random_rotation/fractured_99'
tickness = 0.001
obj_dir = '0408'

os.makedirs(obj_dir, exist_ok=True)

offset_y_list = []
tickness_list = []
tiff_filename_full_list = []
obj_dir_list = []
obj_filename_list = []
for _i, tiff_filename_full in enumerate(tiff_filename_list):
    if _i >= 90 and _i <= 214:
        if (_i - 90) % 6 == 0:
            offset_y_list.append(tickness*_i)
            tiff_filename_full_list.append(tiff_filename_full)
            obj_dir_list.append(obj_dir)
            tickness_list.append(tickness)
    #obj_filename = obj_2_pcd.tiff_2_pcd(tickness*_i, tiff_filename_full, obj_dir, tickness)
    #obj_filename_list.append(obj_filename)


with multiprocessing.Pool() as pool: # Use a pool of 4 processes
    obj_filename_list = pool.starmap(obj_2_pcd.tiff_2_pcd, zip(offset_y_list,tiff_filename_full_list,obj_dir_list, tickness_list))

print(obj_filename_list)
obj_dir = '0408_r'

os.makedirs(obj_dir, exist_ok=True)

angle = random.random()
for obj_filename in obj_filename_list:
    vertices = obj_2_pcd.load_obj(obj_filename)
    vertices, _ = slice_util.random_rotation(vertices, angle)
    with open(obj_dir+"/"+obj_filename.split("/")[-1],'w') as f:
        for xyz in vertices:
            f.write(f'v {xyz[0]} {xyz[1]} {xyz[2]}\n')


import slice_util

slice_util.combine_obj_files(['0408'],'output')
slice_util.combine_obj_files(['0408_r'],'output')

import render_inference_result
import obj_2_pcd
importlib.reload(obj_2_pcd)
importlib.reload(render_inference_result)
img_filename = 'output/0.png'
render_inference_result.pcd_list_2_img(device, obj_filename_list, img_filename,xlim=(0,1),ylim=(0,2),zlim=(-2,2))

from IPython.display import Image
Image(filename=img_filename) 

array([ 0.9516078 ,  0.88325334, -0.9407958 ,  0.53014946,  1.        ,
        0.        ,  0.        ], dtype=float32)

NameError: name 'np' is not defined

In [10]:
torch.device("cuda:0")

device(type='cuda', index=0)

In [7]:
from torch.nn.functional import normalize
t = torch.tensor([torch.rand(1),1,0,0])

t1 = normalize(t, p=1.0, dim = 0)
t1


tensor([0.4745, 0.5255, 0.0000, 0.0000])

In [46]:
predict_0[:,:,5:] = np.zeros((predict_0.shape[0],predict_0.shape[1],2))
predict_0[:,:,4:5] = np.ones((predict_0.shape[0],predict_0.shape[1],1))

In [47]:
predict_0[10,0,3:]

array([-0.2516709,  1.       ,  0.       ,  0.       ], dtype=float32)

In [8]:
x = '/data/jhahn/data/shape_dataset/data/brain_lightsheet/0408/fractured_0/0065.obj'
x.split("/")[-1].split(".")[-2]

'0065'